config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  WillPaginate.per_page = 10

  
end

app/models/article.rb
class Article < ApplicationRecord
    
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 10000}
    WillPaginate.per_page = 10
    
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

    belongs_to :article
    belongs_to :category
    
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    
end

app/models/user.rb
class User < ApplicationRecord

    has_many :articles, dependent: :destroy
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 3, maximum: 25}
        VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105},
        format: {with: VALID_EMAIL_REGEX} 
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
    flash[:danger] = "Action could not be performed."
    redirect_to root_path
    end
  end

  def home_article
    @article = Article.new
  end

  def show_article_on_homepage
    @articles = Article.order("created_at desc").limit(5)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    end

    def show 
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted"
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    
    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "Cannot perform the required action"
            redirect_to root_path
        end
    end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


    before_action :require_admin, only: [:new, :create]
    
    def index
        @categories = Category.paginate(page: params[:page], per_page: 10)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was successfully created"
            redirect_to categories_path(@category)
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Name was updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end

    end

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "Non Authorized action"
            redirect_to categories_path
        end
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        @articles = Article.all
    end

    def about
    end

    def contact
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Failed to Log in"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:danger] = "Successfully logged out"
        redirect_to root_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:edit, :update, :show, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end
   
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to viable #{@user.username}."
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Account updated Successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 10).order('created_at ASC')
    end

    def destroy
        @user.destroy
        flash[:danger] = "Account deleted successfully!" 
        redirect_to root_path
    end

    private
    
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "Action could not be performed"
            redirect_to root_path
        end
    end

    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Action could not be performed"
            redirect_to users_path
        end
    end

end 

app/helpers/application_helper.rb
module ApplicationHelper


    def blog_text_teaser
        @articles = Article.order('created_at DESC').first(4)
    end

    def popular_category
        @categories = Category.all
    end

end

app/views/articles/_article.html.erb
<div class="col-sm-8 col-sm-offset-2 blog-main">
    <div class="center">
        <% obj.each do |article| %>
            <h2 class="blog-post-title article-title"><%= link_to "#{article.title.capitalize}", article_path(article) %></h2>
            <div class="article-meta-details">
                <small> By <%= article.user.username if article.user %> <%= article.created_at.strftime("%B %d %Y")%></small>
                <% if article.categories.any? %>
                    <p>Categories: <%= render article.categories %></p>
                <% end %>
                <% body = article.description || 'No content available' %>
                <p class="body-style index-body"><%= truncate(body, length: 500) %></p>
                <%= link_to "Click here to view more", article_path(article) %>
                <div class="article-actions">
                    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                        <%= link_to "Edit Article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                        <%= link_to "Delete Article", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
                    <% end %>
                </div>
                <hr>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form", multipart: true}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-offset-2 col-sm-8">
                        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                            <% cb.label(class:"checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center"> Edit Article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center" class="title"></h1>

<%= render 'article', obj: @articles %>

<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center" class="article-title"><%= @article.title %> </h2><hr>
<div class="container">

    <div class="col-lg-12 col-lg-offset">
        <% if @article.user %>
            <ul class="listing">
                <div class="row center">
                    <div class="col-md-4 col-md-offset-4">
                        <li>Created By: </li>
                        <li><%= link_to @article.user.username, user_path(@article.user) %></li>
                        <li><small><%= @article.created_at.strftime("%B %d %Y") %></small></li>
                    </div>
                </div>
            </ul>
        <% end %>
        
        <h4 class="center description"><strong>Description</strong></h4>
        <hr>

        <div class="row center body-style">
            <div class="container-fluid">
                <%= simple_format(@article.description) %>
            </div>
        </div>

        <div class="row center body-style">
            <% if @article.categories.any? %>
                <p class>Categories: <%= render @article.categories %></p>
            <% end %>
        </div>

        <hr>

        <div class="row center article-actions">
            <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
            <% end %>
            <%= link_to "Go Back", articles_path, class: "btn btn-xs btn-success" %>
        </div>

    </div>

</div>

app/views/categories/_category.html.erb
<span class="index-style"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form", multipart: true}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Enter Category Name", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 align="Center">Update Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center" class="title">All Categories</h1>
<div align="center"><br>
    <% @categories.each do |category| %>
        <ul class="list-group">
            <div class="container-fluid">
                <div class="row center">
                    <div class="col-lg-4 col-lg-offset-4">
                        <li class="list-group-item article-title">
                        <%= link_to "#{category.name}", category_path(category) %>
                        </li>
                        <li class="list-group-item">
                        <small class="count">
                        <%= pluralize(category.articles.count, "article") %>
                        </small>
                        </li>
                    </div>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="Center">Create Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center" class="title"><%= @category.name %></h1>

<div class="container center">
    <div class="row">
        <% if logged_in? and current_user.admin? %>
            <span class="btn btn-default"><%= link_to "Edit Category", 'edit_category_path(@category)' %>
        <% end %>
    </div>
    <%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div align="center">
    <%= will_paginate @category_articles%>
</div>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
    <div class="footer">
        <small class="footer-text">
            Copyright &copy; 2018 <span class="footer-credits">article.do</span>
            by <a href="https://ashishra0.github.io">Ashish Rao</a>
        </small>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "article.do", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <span><div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"></span>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Blog', articles_path, id: "blog" %></li>
        <li><%= link_to 'Community', users_path, id: "about" %></li>
        <li><%= link_to 'Categories', categories_path, id: "about" %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="dropdown">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Create New Article', new_article_path, id: "action" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Your Articles', user_path(session[:user_id]) %></li>
            <li role="separator" class="divider"></li>
            <% if logged_in? and current_user.admin? %>
            <li><%= link_to 'Create New Category', new_category_path, id: "action" %></li>
            <li role="separator" class="divider"></li>
            <% end %>
          </ul>
        </li>
        <p class="navbar-text navbar-right">Signed in as <%= current_user.username %><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        </p>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in?  %>
          <li><%= link_to 'logout', logout_path, method: :delete, id: "dropdown" %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="dropdown">Your Profile<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Account', edit_user_path(current_user), id: "action" %></li>
            <li><%= link_to 'View Account', user_path(current_user) %></li>
            <li><a href="#"><%="You are Admin" if current_user.admin? %></a></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to 'Already a user? Click to log in', login_path %></li>
          <li><%= link_to 'Sign Up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
  <title>article.do</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application','https://fonts.googleapis.com/css?family=Andika|Bowlby+One+SC|Bungee+Inline|Ceviche+One|Cinzel|Faster+One|Roboto+Slab+Song+Myung+Fascinate+Inline+Bungee+Shade|Fascinate+Inline|Frijole|Shojumaru', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container-fluid home">
    <%= render 'layouts/navigation' %> 
    <%= render 'layouts/messages' %>
    <div class="container-fluid">
    <%= yield %>
    </div>
  </div>
</body>
</html>
<%= render 'layouts/footer' %>

app/views/pages/about.html.erb
<h1> COMING SOON </h1>

app/views/pages/contact.html.erb
<html>
    <h1> Contact Us </h1>
    <body>
        <form>
            <table>
                <tr>
                    <td>Enter Name: <input type="text" value="text" required></td>
                </tr>
                <tr>
                    <td>Enter Mobile No: <input type="text" value="text" required></td>
                </tr>
                <tr>
                    <td>Enter Message <input type="text" value="text" required></td>
                </tr>
            </table>
        </form>
    </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="center jumbotron">
    <span class="color"><h1 class="blog-title">The Blog for everyone</h1></span>
      <div class="container mini-title"><small>Have something interesting? Let the <span class="highlight">world</span> know!</small></h1></div>
        <% if logged_in? != true %>
          <div class="container"><%= link_to 'Get Started', signup_path, class: "btn btn-success btn-lg btn-xlarge" %></div>
        <% end %>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="container-fluid">
        <div class="page-header">
          <h1>Top Articles <small>Updated Every Day</small></h1>
        </div>
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-10">
              <% blog_text_teaser %>
                <% if @articles.present? %>
                  <% @articles.each do |article| %>
                    <h2 class="blog-post-title article-title"><%= link_to "#{article.title.capitalize}", article_path(article) %></h2>
                    <div class="article-meta-details">
                      <small class="user"> By <span class="user-name"><%= article.user.username.capitalize if article.user %></small></small> | <small class="date"><%= article.created_at.strftime("%B %d, %Y")%></small>
                      <% if article.categories.any? %>
                        <p>Categories: <%= render article.categories %></p>
                      <% end %>
                    </div>
                    <% body = article.description || 'No content available' %>
                    <p class="body-style index-body"><%= truncate(body, length: 50) %></p>
                    <%= link_to "Click here to view", article_path(article) %>
                  <% end %>
                <% end %>
              </div>
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="page-header" align="right">
        <h1 align="center">Top Categories</h1>
      </div>
      <ul class="list-group">
        <% popular_category %>
            <% if @categories.present? %>
              <% @categories.each do |category| %>
                <% if category.articles.present? %>
                  <li class="list-group-item list-category">
                    <span class="badge"><%= category.articles.select(:title).count %></span>
                    <%= link_to "#{category.name}", category_path(category) %>
                  </li>
                <% end %>
              <% end %>
            <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibitied the article from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form", multipart: true}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :Username %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
                </div>
            </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :Email %>
            </div>
            <div class="col-sm-8">
                <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :Password %>
            </div>
            <div class="col-sm-8">
                <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-primary btn-lg") %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center"> Update Your Details </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center" class="title">Contributors</h1>
<div align="center"><br>
    <% @users.each do |user| %>
        <ul class="listing">
            <div class="container-fluid">
                <div class="row">
                    <div class="well col-lg-4 col-lg-offset-4">
                        <li class="article-title">
                            <%= link_to user.username, user_path(user) %>
                        </li>
                        <li><small class="count"><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
                        <% if logged_in? and current_user.admin? %>
                            <li><%= link_to "Delete User", user_path(user), method: :delete, data: {confirm: "Proceed with deleting user"} %></li>
                            <li><%= link_to "Edit User", edit_user_path(user) %></li>
                        <% end %>
                    </div>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center"> Sign up </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% if current_user == @user %>
    <h1 align="center"> Howdy <%= @user.username %>!</h1>
<% else %>
    <h1 align="center"><%= @user.username %>'s Articles</h1>
<% end %>

<div class="center">
    <% if @user_articles.count > 0 %>
        <%= will_paginate (@user_articles).order('created_at DESC') %>
    <% else %>
        <div class="well">
            No articles to display
        </div>
    <% end %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
    <%= will_paginate (@user_articles).order('created_at DESC') %>
</div>